### ISSUE TITLE
Award winning software

### ISSUE THREAD

**Issue by vatterspun** [AlexanderPro/SmartSystemMenu#10]
Just making you aware of the fact that SmartSystemMenu beat out a number of other Windows tools in a recent informal competition over at TPFC:

https://www.portablefreeware.com/forums/viewtopic.php?f=2&t=24724

This is a real poll and not an effort to get additional links so please close/delete this case once you've read it.

**Comment by AlexanderPro** [comment]
I appreciate it very much
