### ISSUE TITLE
Issues with Windows Key As Shortcut Modifier

### ISSUE THREAD

**Issue by AaronKnowls** [AlexanderPro/SmartSystemMenu#101]
I'm having issues setting windows key as a modifier.

For example, to use it to minimize windows to tray. I set the hotkey to windows key left or right and the letter T; I close it all, start the software and the window I want to minimize, but it doesn't work. I tried many combinations with the windows key with no luck. It does work if I use other keys.

May it be related to the fact that my keyboard has only one windows key instead of left and right windows keys? Although I guess this is not the issue.

It would be very useful for me being able to use the Windows key since ctrl alt and shift combinations are mostly used by other apps.

Sorry for the long explanation and thank you so much for this amazing software that I use every day.

**Comment by AlexanderPro** [comment]
Hi [AaronKnowls](https://github.com/AaronKnowls),

I have only one keyboard with one windows key "Logitech MX Keys" and everything works correctly for left windows key. Maybe you have some truble with your OS. Does Win+L combination work well with your keyboard?
