### ISSUE TITLE
discord close button not working

### ISSUE THREAD

**Issue by gsrd90** [AlexanderPro/SmartSystemMenu#102]
hello, I discover your software, and the first thing I notice is that the discord close button no longer works when the program is launched. How to make it work again?

**Comment by AlexanderPro** [comment]
Hi [gsrd90](https://github.com/gsrd90),

Unfortunately, SSM is not entirely compatible with Discord. I would recommend adding the discord.exe to "System Tray" menu | "Settings" item | "General" tab | "Process Exclusions" list

**Comment by gsrd90** [comment]
thanks for answering, process exclusion additions are supposed to be effective after software restart but it is not, everything is taken into account after system restart.

is it possible to apply the changes without having to restart the software each time? it's quite annoying...

**Comment by AlexanderPro** [comment]
Hi @gsrd90,

Please, try version [2.25.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.25.0/SmartSystemMenu_v2.25.0.zip). But there is a possibility that discord system menu will be shown after the second call.
