### ISSUE TITLE
[Request] Pls add save screenshot to clipboard

### ISSUE THREAD

**Issue by Akira28hk** [AlexanderPro/SmartSystemMenu#103]
Pls add screenshot save to clipboard instead file, many thanks

**Comment by Akira28hk** [comment]
Thank you very much!! Looking forward to get this on release

**Comment by AlexanderPro** [comment]
Hi [Akira28hk](https://github.com/Akira28hk),
Please, try version [2.23.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v2.23.0).
