### ISSUE TITLE
Wasting RegisterWindowMessage

### ISSUE THREAD

**Issue by sredna** [AlexanderPro/SmartSystemMenu#109]
RegisterWindowMessage is a shared global resource that you cannot free back to the system, they stick around for the lifetime of the session.

You are sending messages to a specific window so you don't even need RegisterWindowMessage, you can use messages in the WM_APP range.

**Comment by AlexanderPro** [comment]
Hi @sredna ,
Thank you. It works. Version [2.24.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v2.24.0).
