### ISSUE TITLE
Always on Top not working with AIMP

### ISSUE THREAD

**Issue by JoaquinSuez** [AlexanderPro/SmartSystemMenu#113]
Self descriptive. If there is any information I can provide i'd be happy to do so.

**Comment by AlexanderPro** [comment]
Hi @JoaquinSuez,

Does AIMP have a system menu? What AIMP version do you use? As I know AIMP has its own menu, not a system.

**Comment by JoaquinSuez** [comment]
Hey. Sorry, I missed your reply. Yes, it has it's own menu, but the problem is with it's audio converter utility. I can click on the AoT button but it does nothing. Other system menu projects like this have the same problem.
