### ISSUE TITLE
[feature request] shortcut to resize windows

### ISSUE THREAD

**Issue by iamqiz** [AlexanderPro/SmartSystemMenu#116]
some exe can not support alt+space to open its window menu,  how do i resize it ? thanks

**Comment by AlexanderPro** [comment]
Hi @iamqiz,

Could you provide an example of your software?

**Comment by iamqiz** [comment]
@AlexanderPro League of Legends (by Riot Games)😄

**Comment by AlexanderPro** [comment]
I'll try to add a context menu (by hotkeys) to windows with all SSM items in the next versions.

**Comment by iamqiz** [comment]
@AlexanderPro thanks!😘

**Comment by AlexanderPro** [comment]
Hi @iamqiz,

Try to use [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu) instead of SSM. Default hotkeys “**Ctrl + Right Mouse Button**”. In some OS there can be a few seconds delay after the start of SmartContextMenu from time to time.

**Comment by iamqiz** [comment]
@AlexanderPro I tried the SCM, it work~ thanks~
by the way, it trim the window,instead of scaling it, is that purposive?

**Comment by AlexanderPro** [comment]
@iamqiz, what menu item and window do you use? If possible please attach a screenshot.

**Comment by iamqiz** [comment]
@AlexanderPro   menu item: "resize",
 window: League of Legends (by Riot Games)
# resize to 640*480: 
![Snipaste_环境返回_2023-12-22__21-20-44](https://github.com/AlexanderPro/SmartSystemMenu/assets/48077521/68cc2e89-1d45-4b4e-8387-d843e6cf724a)

# resize to 1024*768:
![Snipaste_环境返回_2023-12-22__21-21-06](https://github.com/AlexanderPro/SmartSystemMenu/assets/48077521/5dceff94-69db-43df-af8a-c0bf2580404e)

you can see that when 640*480, some parts of window are not be displayed 

I have tried another tool named "sizer" (https://www.brianapps.net/sizer4/), it have same result . so it seemly is hard to solve,  never mind , the SCM is good enough now 😄
