### ISSUE TITLE
FAR и наверное другие консольные окна

### ISSUE THREAD

**Issue by skuwakin** [AlexanderPro/SmartSystemMenu#118]
На окне FARa вызываю меню программы, и в нем не работает ничего из попробованных, как-то INFO, размер и даже запуск блокнота и калькулятора. Если что, программа запускалась из "E:\Program Files\SSM\" 

p.s. Ну и просто не понятно, а как пользоваться этой шикарной программой на столь сейчас модных окнах без заголовков окна, например, едге, телеграм и т.п.

**Comment by AlexanderPro** [comment]
@skuwakin, добрый день. 

К сожалению не все процессы и их окна работают одинаково. Ошибку воспроизвел на Far, при этом cmd и PowerShell отрабатывают нормально. И ошибка связана с тем, что хуки не грузятся в уже запущенный процесс far.exe. Если Far запустить после SSM, хуки загрузятся и меню должно отрабатывать. Если пойму в чём причина, постараюсь поправить. Решение для окон без заголовков надеюсь скоро тоже реализую.

**Comment by skuwakin** [comment]
Доброго времени суток. Спасибо за ответ.  Про FAR понял, жаль, ибо насколько я понимаю, ситуёвина хреноватенькая...Но... как говорилось в одном зорошем киножурнале "мы не привыкли отступать".  Так что от души желаю успехов  Так как  Ваша программа из серии "мал, да удал".  Таких программ не так много...  ИИНО. P..S. Про программы без заголовков окна.  позволю себе подать Вам идею.    Она не моя,  и название проги не вспоминается, но смысл таков, на окно нужной проги бросается нечто,  ну например иконка, и по результату завершения dragdrop можно вывести меню Вашей проги, которое выводится при клике на иконку  заголовка окна.  Ест-но всё ИМНО.  Отправлено из приложения "Почта" для Windows От: Alexander IllarionovОтправлено: 12 ноября 2023 г. в 22:59Кому: AlexanderPro/SmartSystemMenuКопия: skuwakin; MentionТема: Re: [AlexanderPro/SmartSystemMenu] FAR и наверное другие консольные окна (Issue ***@***.***, добрый день.К сожалению не все процессы и их окна работают одинаково. Ошибку воспроизвел на Far, при этом cmd и PowerShell отрабатывают нормально. И ошибка связана с тем, что хуки не грузятся в уже запущенный процесс far.exe. Если Far запустить после SSM, хуки загрузятся и меню должно отрабатывать. Если пойму в чём причина, постараюсь поправить. Решение для окон без заголовков надеюсь скоро тоже реализую.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by AlexanderPro** [comment]
@skuwakin, добрый день.

Если еще актуально попробуйте новое приложение [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu), должно поддерживать Far. По умолчанию горячие клавиши “**Ctrl + правая кнопка мыши**”. Иногда после запуска SmartContextMenu может происходить задержка в несколько секунд после чего начинают работать горячие клавиши.
