### ISSUE TITLE
fix(menu): retain 'Edit', 'Defaults', 'Properties' menu items

### ISSUE THREAD

**Issue by samkatakouzinos** [AlexanderPro/SmartSystemMenu#12]
Please retain these menu items for windows such as;
- Command Prompt
- Windows PowerShell
- PowerShell Core

They are;
- Edit
- Defaults 
- Properties

Example image shown;

 ![HpPBUNAvu4](https://user-images.githubusercontent.com/1305871/76578407-95817380-651c-11ea-9512-5da5b89b433c.png)

I would like these menu items to remain in addition to the extra menu items created with this software.

— Regards, Sam Katakouzinos

**Comment by AlexanderPro** [comment]
Hi Sam,

Please, try this version [1.7.2](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/1.7.2/SmartSystemMenu_v1.7.2.zip)

— Regards, Alexander Illarionov

**Comment by samkatakouzinos** [comment]
I've tested https://github.com/AlexanderPro/SmartSystemMenu/tree/1.7.2 
It works correctly. 
Thank you for solving this request.
