### ISSUE TITLE
[Feature Request] Hide SmartSystemMenu task icon

### ISSUE THREAD

**Issue by alexceltare2** [AlexanderPro/SmartSystemMenu#120]
Can you add a feature to Hide the SmartSystemMenu icon from taskbar (background only)?

**Comment by AlexanderPro** [comment]
Hi @alexceltare2 ,

The SSM icon can be hidden from the System Tray by systemTrayIcon tag in the SmartSystemMenu.xml file.

```
<systemTrayIcon show="false" />
```
