### ISSUE TITLE
how to reinstall

### ISSUE THREAD

**Issue by just39** [AlexanderPro/SmartSystemMenu#127]
I accidentally deleted the folder, downloaded the compressed file again, decompressed it, and when I opened it again, I found that it couldn't start

**Comment by AlexanderPro** [comment]
Hi @just39,

Please, try just to relogin or reboot your OS and start SSM

**Comment by just39** [comment]
> Hi @just39,
> 
> Please, try just to relogin or reboot your OS and start SSM

Thank you for your reply. I have found another software called smartcontextmenu to replace it

**Comment by AlexanderPro** [comment]
Yes, I would recomend to use [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu) instead of SmartSystemMenu, because SCM doesn't have such problems as SSM.
