### ISSUE TITLE
Exception now and then

### ISSUE THREAD

**Issue by kintrupf** [AlexanderPro/SmartSystemMenu#13]
I have not yet figured out when this exception really occurs. Usually I find this dialog on my screen after I left the computer unattended for some time. It only happens every few days, but on two different computers, so it might not be a local phenomenon.

![2020-06-14 08_52_51-Window](https://user-images.githubusercontent.com/8496344/84592041-e74ed800-ae42-11ea-9290-8385a919ed7b.png)
.

**Comment by AlexanderPro** [comment]
Hi kintrupf,

Please, try this version [1.7.3](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/1.7.3/SmartSystemMenu_v1.7.3.zip)

— Regards, 
Alexander Illarionov

**Comment by kintrupf** [comment]
I installed the 1.7.3. release a few weeks ago and had absolutely no exceptions since then.
So the problem seems to be solved with that release!
Thanks for your effort 😀

**Comment by AlexanderPro** [comment]
You are welcome)
