### ISSUE TITLE
Couldn't find entry point 'InitializeMouseHook' in 'SmartSystemMenuHook64.dll' in version 2.27.1

### ISSUE THREAD

**Issue by skychomper** [AlexanderPro/SmartSystemMenu#139]
In version 2.27.0 this error does not occur.

![2024-09-09 10_04_58-Smart System Menu](https://github.com/user-attachments/assets/6766c5e0-7f52-40bd-b24d-5e3309149f87)

Windows 10 Pro 22H2 build 19045.4651
Windows Feature Experience Pack 1000.19060.1000.0

**Comment by AlexanderPro** [comment]
Hi @skychomper,

Please, reboot or relogin your OS.  Try to remove all unpacked folders with the previous versions of SSM. Unzip SmartSystemMenu_v2.27.1.zip and run SmartSystemMenu.exe again. I also do not recommend to copy SmartSystemMenuHook.dll and SmartSystemMenuHook64.dll files to the previous unpacked folders or vice versa.
