### ISSUE TITLE
Hide tray icon option

### ISSUE THREAD

**Issue by qupear** [AlexanderPro/SmartSystemMenu#14]
Feature suggestion to add an option for hiding SmartSystemMenu icon in system tray.

**Comment by AlexanderPro** [comment]
Hi qupear,

Please, try this version [1.7.3](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/1.7.3/SmartSystemMenu_v1.7.3.zip)

— Regards, 
Alexander Illarionov

**Comment by qupear** [comment]
Thank you very much!

**Comment by AlexanderPro** [comment]
Hi @win98se,
This option has always been only in the SmartSystemMenu.xml file (systemTrayIcon tag).

**Comment by AlexanderPro** [comment]
There may be some settings on your PC that are affecting the issue. On my PC and laptop with Windows 10 everything works correctly.
