### ISSUE TITLE
关于在其他显示器字体的问题

### ISSUE THREAD

**Issue by li5bo5** [AlexanderPro/SmartSystemMenu#151]
右键任务栏的图标，显示字体模糊
![1](https://github.com/user-attachments/assets/5251d048-789f-4117-bdac-743d08d40bcd)
![2](https://github.com/user-attachments/assets/814aa231-fcbf-4667-b8d3-4ca1504aee84)
![3](https://github.com/user-attachments/assets/cf5a9336-6848-4979-80ee-2bac46772e5c)

**Comment by li5bo5** [comment]
![4](https://github.com/user-attachments/assets/5f427524-4b6c-4683-a4ba-3bac4130b8d0)

**Comment by AlexanderPro** [comment]
Hi @li5bo5,

Open the SmartSystemMenu.xml file and edit section:
```
 <display highDPI="false" />
```
 to
```
 <display highDPI="true" />
```

**Comment by li5bo5** [comment]
yes！
