### ISSUE TITLE
Breaks certain windows apps

### ISSUE THREAD

**Issue by Yoshi8765** [AlexanderPro/SmartSystemMenu#2]
Hello,
I think SmartSystemMenu is interfering with certain windows programs, such as Discord and Slack. SSM makes the programs not able to be minimized after one try.

**Comment by AlexanderPro** [comment]
Hello,
I have disabled hooks for Discord and Slack apps in this version
https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v1.1.6864.30145
