### ISSUE TITLE
Possible could maintain package on chocolatey repository?

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [AlexanderPro/SmartSystemMenu#21]
I found this outdated:
[https://chocolatey.org/packages/smartsystemmenu#versionhistory](url)
And it would Be more trustworthy from packager.
There seems to be multiple hundreds of users from this repo.

**Comment by samkatakouzinos** [comment]
I use Chocolatey for systems management. 
I agree it would be great if you would maintain and update this package over at https://community.chocolatey.org/packages/smartsystemmenu please.
