### ISSUE TITLE
Add posibility to disable some menu options

### ISSUE THREAD

**Issue by sebthom** [AlexanderPro/SmartSystemMenu#24]
Maybe it is possible already, but I would like to remove some of the added system menu options as I am not using them and so they just clutter the system menu. E.g. "Roll Up", "Aero Glass", "Drag By Mouse", "Start Program".

Thanks for this handy tool!

**Comment by AlexanderPro** [comment]
Hi sebthom,

Please, try this version [2.3.1](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.3.1/SmartSystemMenu_v2.3.1.zip)

— Regards, 
Alexander Illarionov

**Comment by sebthom** [comment]
Awesome, thanks!
