### ISSUE TITLE
[Feature Request]Reorder menù items + mouse gestures

### ISSUE THREAD

**Issue by ramalina** [AlexanderPro/SmartSystemMenu#25]
Hello,
first of all many thanks for SmartSystemMenu, simple perfect menu.

I'm writing to ask if would be possibile to move or reorder menu items, in particular I'd like to have minimize to tray as a choice in the first level of the menu (and not in the submenu "system tray".

Thank you.

**Comment by netsonicyxf** [comment]
I also like the "reorder menu items" feature.

**Comment by AlexanderPro** [comment]
Fixed
