### ISSUE TITLE
Affects software that use vJoy

### ISSUE THREAD

**Issue by samkatakouzinos** [AlexanderPro/SmartSystemMenu#28]
Hi there. 

Software configured to receive events from virtual joysticks via vJoy do so slowly. 
I run vJoy, Joystick Gremlin and joystick devices like steering wheels, pedals, gear shifters. 

I define mappings in Joystick Gremlin. One is pressing a real button on a steering wheel will activate a virtual button on a virtual joystick. 
Then other software such as discord, teamspeak are configured to keybind to that virtual button to mute voice. 

With SmartSystemMenu 2.4.1 running vJoy events run delayed and no guarantee when it will be delivered. 
Can range from one second to over a minute. This is unacceptable for me. 
The more programs I run the longer it takes and I run many programs. 

Without SmartSystemMenu 2.4.1 running vJoy events run instantly with no delay. 

May you know why SmartSystemMenu impacts the use of vJoy so much? 
For now I've turned off SmartSystemMenu so that my system is responsive. 

— Regards, Sam Katakouzinos 

References: 
https://github.com/shauleiz/vJoy/releases/tag/v2.1.8.39 
https://github.com/WhiteMagic/JoystickGremlin/releases/tag/Release_13.3

**Comment by AlexanderPro** [comment]
Hi Sam.

If it is still relevant, I don't know the exact reason for the error, but you can try to resolve it by the next steps:

1. Download version  [2.9.3](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.9.3/SmartSystemMenu_v2.9.3.zip)
2. In the settings dialog (Menu tab) disable all the hot keys.
3. In the settings dialog (Menu tab) hide menu item "Drag By Mouse".
4. Or just save the file with the settings (for the second and third steps) from [here](https://github.com/AlexanderPro/SmartSystemMenu/files/6986321/SmartSystemMenu.xml.zip).

**Comment by samkatakouzinos** [comment]
> you can try to resolve it by the next steps:

I used version 2.9.3 as well as your settings file.  

The issue is still present unfortunately. 
I'm happy to trial other things to try to resolve this issue.

**Comment by AlexanderPro** [comment]
As another solution, you can try to add proccesses (vJoy, JoystickGremlin) in the settings dialog (General tab | Process Exclusions).

**Comment by samkatakouzinos** [comment]
> As another solution, you can try to add proccesses (vJoy, JoystickGremlin) in the settings dialog (General tab | Process Exclusions).

I'm unsure how the hooks work with files. 
Is it only executables (*.exe) that can be listed? Can dynamic link library files (*.dll) be listed?

**Comment by AlexanderPro** [comment]
Hooks are injected in the process files (.exe). So you should use only .exe files in the settings dialog (General tab | Process Exclusions).

**Comment by samkatakouzinos** [comment]
I've been adding process files to the exclusions list but doesn't seem to help the issue. 

It seems that vJoy and Joystick Gremlin have no delays with a few apps running with SmartSystemMenu. 

It seems that vJoy and Joystick Gremlin start having delays after many apps are running with SmartSystemMenu. 
When stopping SmartSystemMenu the delays are removed. 

Any other suggestions?

**Comment by AlexanderPro** [comment]
Hi Sam,

Try to use [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu) instead of SSM. It should be more stable and lightweight. Default hotkeys “**Ctrl + Right Mouse Button**”. In some OS there can be a few seconds delay after the start of SmartContextMenu from time to time.

**Comment by samkatakouzinos** [comment]
> Hi Sam,
> 
> Try to use [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu) instead of SSM.

Thank you, will do so.
Closing this issue.
