### ISSUE TITLE
Alignment overlay

### ISSUE THREAD

**Issue by qupear** [AlexanderPro/SmartSystemMenu#29]
When align by the bottom edge of screen, windows are positioned so that there is a little overlay. Bottom side of aligned window is about 20 pixels below the bottom edge of the screen. So that I need to move every aligned window a little upper manually. Would be better if bottom of aligned application is several pixels above the screen edge. With other edges no such issues.

**Comment by qupear** [comment]
Понял в чём причина. Это из-за того, что панель задач сверху экрана, а не снизу как обычно. Если поместить панель вниз, то SSM выравнивает окна корректно.

**Comment by AlexanderPro** [comment]
Я посмотрю в ближайшее время. По хорошему окно не должно выходить за пределы экрана. Если есть возможность приложите скриншот.

**Comment by qupear** [comment]
![taskbar-overlay](https://user-images.githubusercontent.com/8069685/123067739-ec614280-d419-11eb-9b63-d3b7b3ea10cf.png)

**Comment by qupear** [comment]
![taskbar-overlay](https://user-images.githubusercontent.com/8069685/123068580-b07aad00-d41a-11eb-9229-a5b102c57164.png)

**Comment by qupear** [comment]
https://user-images.githubusercontent.com/8069685/123069108-2717aa80-d41b-11eb-8958-fa978385eb22.mp4

**Comment by AlexanderPro** [comment]
Попробуйте версию [2.6.1](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.6.1/SmartSystemMenu_v2.6.1.zip)

**Comment by qupear** [comment]
Спасибо!
