### ISSUE TITLE
Disable / no hotkey version?

### ISSUE THREAD

**Issue by kulmegil** [AlexanderPro/SmartSystemMenu#3]
Non configurable, global hotkeys are a terrible idea.
Especially such as ctrl+shift+arrrow_down that conflicts with many IDEs and text editors.

Is there a way to disable this? Or can we get a version without any global hotkeys hard-coded?

**Comment by AlexanderPro** [comment]
Hello,
I have disabled hotkeys, in this version
https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v1.1.6864.30145

**Comment by kulmegil** [comment]
Thank You. Exactly what kept me from using it daily.
