### ISSUE TITLE
Telegram, Conemu errors

### ISSUE THREAD

**Issue by qupear** [AlexanderPro/SmartSystemMenu#30]
Иногда выскакивают такие ошибки
![image](https://user-images.githubusercontent.com/8069685/123932303-fba43b00-d999-11eb-8f23-c54b565b2f87.png)
![image](https://user-images.githubusercontent.com/8069685/123932409-18d90980-d99a-11eb-9bd3-633de2855fd0.png)
Предположительно, вызвано это открытием окон Telegram.exe и Conemu64.exe.

**Comment by AlexanderPro** [comment]
Похоже ошибка появилась в последней или предпоследней версии. В ближайшее время поправлю.

**Comment by sebthom** [comment]
I am having the same issue. When turning on/off an external monitor on my laptop.

![image](https://user-images.githubusercontent.com/426959/125159111-a3c5bb00-e175-11eb-8bc8-7461bd55b7a2.png)

**Comment by AlexanderPro** [comment]
Hi qupear and sebthom,

Please, try version  [2.6.2](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.6.2/SmartSystemMenu_v2.6.2.zip)

**Comment by sebthom** [comment]
@AlexanderPro seems to work for me. thanks!

**Comment by AlexanderPro** [comment]
Unfortunately, SmartSystemMenuHook.dll and SmartSystemMenuHook64.dll files can be unloaded only in several minutes or more. 
I cannot fix it yet. The only one solution I know is to relogin(reboot) or kill the proces which holds the file.
