### ISSUE TITLE
Resize client area

### ISSUE THREAD

**Issue by mjarr** [AlexanderPro/SmartSystemMenu#31]
Currently the resize utility sets the window size directly, which includes the size of window decorations. It results in the client area being smaller than expected and makes it awkward to use it for resizing games.

Would it be possible to add an alternative behavior that seeks to reach the given client size instead?

**Comment by AlexanderPro** [comment]
Hi mjarr,

Please, try version  [2.9.1](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.9.1/SmartSystemMenu_v2.9.1.zip). You should select in the Settings Dialog:
Tab Menu (Resize) -> How to set window size ->Window without margins

**Comment by mjarr** [comment]
It doesn't work unfortunately.
Resizing to 640x480 with the default behavior results in client area of 634x451, the new one results in client area of 638x453.

I think setting the window size to WindowRect + (WindowRect - ClientRect) should fix it.

**Comment by AlexanderPro** [comment]
Please, try version  [2.9.2](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.9.2/SmartSystemMenu_v2.9.2.zip). You should select in the Settings Dialog:
Tab Menu (Resize) -> How to set window size ->Window client area

**Comment by mjarr** [comment]
It works great now. Thanks.

Consider including 1280x720 in the default config by the way.
