### ISSUE TITLE
Системный трей

### ISSUE THREAD

**Issue by Prothet** [AlexanderPro/SmartSystemMenu#35]
Если в настройках снять галочку с пункта "Системный трей", то все окна начинают сворачиваться  в системный трей.

**Comment by AlexanderPro** [comment]
Попробуйте версию  [2.9.4](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.9.4/SmartSystemMenu_v2.9.4.zip)

**Comment by Prothet** [comment]
Все работает правильно
