### ISSUE TITLE
Изменить размер

### ISSUE THREAD

**Issue by Prothet** [AlexanderPro/SmartSystemMenu#36]
Хотелось бы иметь именованные (сейчас в качестве наименования используется размер) комбинации размера и позиции - координат левого верхнего угла (позиции сейчас нет)

**Comment by AlexanderPro** [comment]
Попробуйте версию  [2.10.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.10.0/SmartSystemMenu_v2.10.0.zip)
