### ISSUE TITLE
Is there an setting to disable the 'minimize to tray' feature?

### ISSUE THREAD

**Issue by LupusHacker** [AlexanderPro/SmartSystemMenu#37]
Noticed that in some cases the icon for the program will just disappear, even though it's still running in the background, and I'd rather not have to deal with accidentally opening another instance of an intensive program.

**Comment by AlexanderPro** [comment]
Could you please provide the sequence of steps you made? To hide "Minimize To Tray" menu item you need to disable it in the "Settings" dialog ("Menu" tab | uncheck the item).

**Comment by LupusHacker** [comment]
> Could you please provide the sequence of steps you made? To hide "Minimize To Tray" menu item you need to disable it in the "Settings" dialog ("Menu" tab | uncheck the item).

Opened Chrome, minimized outside the system tray > Opened VRC > Attempted to open Chrome suspended near the system tray, instantly disappeared along with an indicator it was active > Closed VRC and opened Task Manager, Chrome was running in the background > Restored tabs like nothing happened

**Comment by AlexanderPro** [comment]
Sorry for the late response, try version  [2.17.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.17.0/SmartSystemMenu_v2.17.0.zip)

**Comment by LupusHacker** [comment]
This is now an older issue. It's now the opposite with the newer version, as I'm sticking with the current one.
