### ISSUE TITLE
Add exclusions

### ISSUE THREAD

**Issue by SpringsTS** [AlexanderPro/SmartSystemMenu#4]
At first, thank you for this software!

Now for the issue:
I use UltraVNC. This software has its own system context menu.
When I launch SmartSystemMenu, the UltraVNC's menu is removed and replaced by SmartSystemMenu's one.
This may come from the "Limitations" part you mentioned in your main page.

Could it be possible to add exclusions to your software, to ignore specific windows / applications? That would be fantastic.
Thank you in advance.

**Comment by AlexanderPro** [comment]
Hello,
I have added a file with process names to be excluded, in this version
https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/1.1.6902.39552
