### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by WelshSpringer** [AlexanderPro/SmartSystemMenu#44]
It would be great to be able to make command line use of SMM from batch file scripts. This would only be useful if it didn't interfere with SMM also running in the background for normal right click on window title access.

For example:

:
start Notepad %1
SmartSystemMenu.exe /window="Notepad" /moveto=monitor2 /align=MiddleCentre /alwaysOnTop
:

**Comment by AlexanderPro** [comment]
Hi WelshSpringer,

Please, try version  [2.13.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.13.0/SmartSystemMenu_v2.13.0.zip)

**Comment by WelshSpringer** [comment]
Thanks, that works very well, very useful improvement to the feature set.
