### ISSUE TITLE
[Suggest] Add high DPI support

### ISSUE THREAD

**Issue by EVANGELION-Air** [AlexanderPro/SmartSystemMenu#48]
Although the right-click menu is implemented by the system and has no scaling problem, the Setting and the Information tool (or other program interface) was poorly display on high DPI screens, even if change system DPI compatibility of SmartSystemMenu.exe in the property setting, it still has not a good effect.

**Comment by AlexanderPro** [comment]
Hi EVANGELION-Air,

Please, try version  [2.14.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.14.0/SmartSystemMenu_v2.14.0.zip)

**Comment by EVANGELION-Air** [comment]
> Hi EVANGELION-Air,
> 
> Please, try version [2.14.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.14.0/SmartSystemMenu_v2.14.0.zip)

The new version works very well on High DPI screens, thank you very much for your work!

**Comment by AlexanderPro** [comment]
To enable high DPI, please use version [2.17.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.17.0/SmartSystemMenu_v2.17.0.zip), "Settings" dialog "General" tab.
