### ISSUE TITLE
[Suggest] Custom Menu Entry

### ISSUE THREAD

**Issue by jean3x7** [AlexanderPro/SmartSystemMenu#50]
Please add an option to create custom menu/submenu item with window parameters ex: 

"Force Kill": taskkill /f /im %process_name%
"Force Kill PID": taskkill /f /PID %process_id%
"Search Web (Windows Title)": chrome.exe "https://www.google.com/search?q=%window_title%"
"Search Web (Process Name)": chrome.exe "https://www.google.com/search?q=%process_name%"

Checkbox option to choose if want to run hidden

thanks.

**Comment by AlexanderPro** [comment]
Hi jean3x7,

Please, try version  [2.15.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.15.0/SmartSystemMenu_v2.15.0.zip)

I have added new menu items with parameters:
- Start Program | Kill Process
- Start Program | Kill Process PID
You can add items with parameters to "Start Program" menu. All options for such items are available in the Settings dialog | Menu (Start Program) tab.

**Comment by jean3x7** [comment]
Thanks for reply, i tried 2.15.0 version, works, but it prompt to input information. 
I suggest to run commands with current window paramentes, ex:

If i created a custom entry to "Force Kill": taskkill /f /im %process_name%

If I open notepad.exe, then click on the menu to "Force delete", the command I run should be:  "taskkill /f /im notepad.exe"

SmartSystemMenu will replace %process_name% with "notepad.exe" (current window)

![image](https://user-images.githubusercontent.com/32421544/145139024-5ba5cbeb-d063-4350-a686-d13ada6bb5f8.png)

**Comment by AlexanderPro** [comment]
Why would you like to have two menu items "Force Kill" and "Force Kill PID", not one?  Do you intend to kill several processes by name (e.g. notepad.exe)?

**Comment by jean3x7** [comment]
> Why would you like to have two menu items "Force Kill" and "Force Kill PID", not one? Do you intend to kill several processes by name (e.g. notepad.exe)?

Whatever, just an example, my suggestion is to create custom menu entry with configurable command using current window parameters like window title, process name, process id, etc.

**Comment by AlexanderPro** [comment]
Try version  [2.15.1](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.15.1/SmartSystemMenu_v2.15.1.zip)

I have added three parameters process_id, process_name, window_title and new menu item Start Program | Kill This Process.
If you would like to add menu items "Search Web (Windows Title)" or "Search Web (Process Name)", use this confgiguration file: [SmartSystemMenu.xml.zip](https://github.com/AlexanderPro/SmartSystemMenu/files/7696813/SmartSystemMenu.xml.zip)

**Comment by jean3x7** [comment]
Thanks, this will be enough to extend the functionality for any situation.
