### ISSUE TITLE
end of support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [AlexanderPro/SmartSystemMenu#54]
2.13.1 is the last version for Windows XP.
the newer releases are not supported anymore.

**Comment by AlexanderPro** [comment]
Please, try version  [2.17.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.17.0/SmartSystemMenu_v2.17.0.zip)

**Comment by AlexanderPro** [comment]
Fixed

**Comment by andika207** [comment]
fixed what ? the 2.17 has been working flawlessly
