### ISSUE TITLE
[Feature Request] Extra alignment options

### ISSUE THREAD

**Issue by WelshSpringer** [AlexanderPro/SmartSystemMenu#55]
In addition to the current alignment, it would be nice to have these two separate actions:

**Centre horizontally**                    (no vertical change)
**Centre vertically**                        (no horizontal change)

**Comment by AlexanderPro** [comment]
Please, try version  [2.18.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.18.0/SmartSystemMenu_v2.18.0.zip)

**Comment by WelshSpringer** [comment]
Works perfectly, thank you!
