### ISSUE TITLE
Context menu for exiting the program in the tray

### ISSUE THREAD

**Issue by oleg-sgh** [AlexanderPro/SmartSystemMenu#56]
Hello.
Is it possible to make an option to exit the program, collapsed in the tray, by clicking the **right** mouse button.
Example
![2022-01-11_144109](https://user-images.githubusercontent.com/43082921/148920722-94b81586-95f4-4fa3-b5da-b62fbf9c5543.png)

**Comment by AlexanderPro** [comment]
Hi,

The left mouse button is used to restore the window. Could it be better to use the right button and display a menu in the system tray with two items "Restore" and "Exit"?

**Comment by WelshSpringer** [comment]
Agree, it's fine as it is.

**Comment by oleg-sgh** [comment]
> Привет,
> 
> Левая кнопка мыши используется для восстановления окна. Может быть лучше использовать правую кнопку и вывести в системный трей меню с двумя пунктами "Восстановление" и "Выход"?

Yes, I was mistaken, confused the mouse buttons - sorry. Right-click on the tray - exit in the context menu.

**Comment by AlexanderPro** [comment]
Please, try version  [2.18.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.18.0/SmartSystemMenu_v2.18.0.zip)

**Comment by oleg-sgh** [comment]
Thanks.

**Comment by WelshSpringer** [comment]
Works perfectly, thank you!

-- David

________________________________
