### ISSUE TITLE
[Feature Request] Remember different settings for different apps

### ISSUE THREAD

**Issue by netsonicyxf** [AlexanderPro/SmartSystemMenu#57]
For example, I want to apply "always minimize to tray" to X1 app, 
and apply "always on top" to X2 app.
when SSM launches.
and I can temporarily disable these settings.

**Comment by netsonicyxf** [comment]
But there is no feature in the SSM to remember these settings for apps

**Comment by AlexanderPro** [comment]
Hi netsonicyxf,

I am going to add this feature in the next versions.

**Comment by netsonicyxf** [comment]
Hi Alexander，

Looking forward to see the next version.
Thank you!

**Comment by AlexanderPro** [comment]
Duplicate of #61
