### ISSUE TITLE
How to activate the window after the transparency is set to 100%?

### ISSUE THREAD

**Issue by xiers819** [AlexanderPro/SmartSystemMenu#60]
The windows will be invisible if its transparentcy be set to 100%(invisible), in that case, how can i reactivate and reset it?

**Comment by koji-takahiro** [comment]
Run SSM via console with transparency settings > 0% :
`SmartSystemMenu.exe --title [Window Title ] --transparency [0 ... 100]`
Look at the help [README.md](https://github.com/AlexanderPro/SmartSystemMenu/blob/master/README.md)

**Comment by AlexanderPro** [comment]
Hi [xiers819](https://github.com/xiers819),
Please, try version [2.23.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v2.23.0). To restore transparency, use systemtray "Restore | Transparency" menu item.
