### ISSUE TITLE
release a SmartSystemMenu64.exe at erevy runtime？why？

### ISSUE THREAD

**Issue by Tback1** [AlexanderPro/SmartSystemMenu#62]
release a SmartSystemMenu64.exe at the local folder erevy runtime，then close application will delete it.
and next will release it again

Why not persistent the x64.exe under the folder??

SmartSystemMenu 2.19
Win 10 2021 LTSB

**Comment by AlexanderPro** [comment]
Hi @Tback1,

Try to use [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu) instead of SSM. It consists of a singular executable file. Default hotkeys “**Ctrl + Right Mouse Button**”. In some OS there can be a few seconds delay after the start of SmartContextMenu from time to time.

**Comment by Tback1** [comment]
thanks，I will try it
