### ISSUE TITLE
[Question] How to Autostart upon Login

### ISSUE THREAD

**Issue by valsamis-d** [AlexanderPro/SmartSystemMenu#64]
**(*) Edit: Nevermind guys. I figured it out :)**

Hi,

I tried to find some short of settings panel, but didn't find any neither a taskbar icon. How, do I enable autostart whenever I reboot and login to my Windows 10 account?

Thanks

**Comment by AlexanderPro** [comment]
Hi valsamis-d,

You can use a system tray icon with a context menu "Auto start program"
