### ISSUE TITLE
Feature request: copy open file path to clipboard

### ISSUE THREAD

**Issue by valuex** [AlexanderPro/SmartSystemMenu#65]
Nice work! Could you add these feature?
- copy open file title to clipboard
- copy open file full path to clipboard
- browse open file in explorer

Thanks.

**Comment by AlexanderPro** [comment]
Hi valuex,

Please, try version  [2.19.2](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.19.2/SmartSystemMenu_v2.19.2.zip)

I have added two menu items "Clipboard | Copy Window Title" and "Clipboard | Copy Full Process Path". Menu item "Open File In Explorer" already exists.
