### ISSUE TITLE
PotPlayer player

### ISSUE THREAD

**Issue by oleg-sgh** [AlexanderPro/SmartSystemMenu#66]
Resizing and moving with hotkeys do not work in the PotPlayer player.  SSM version 2.19.2
PotPlayer player has no SSM menu.
In version 2.18.0 it works.

Windows 7х64. 
PotPlayer https://potplayer.daum.net/

add
Missing SSM menu in File Explorer dialogs.
In version 2.18.0 it works.

**Comment by netsonicyxf** [comment]
I found that lots of SSM-like softwares do not work with pot player

**Comment by oleg-sgh** [comment]
Now the previous version 2.18.0 is installed and it works.
The previous versions worked the same way.
The problem started in versions 2.19.0 and 2.19.2.

**Comment by AlexanderPro** [comment]
Please, try version  [2.19.3](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.19.3/SmartSystemMenu_v2.19.3.zip)

**Comment by oleg-sgh** [comment]
Thanks.

**Comment by vxbmtu94516** [comment]
i know is that changing the skin works :laughing:
https://www.deviantart.com/mr-web/art/XMP-ITA-Win7-Skin-for-PotPlayer-674823052

![Windows 7-2022-03-06-18-01-30](https://user-images.githubusercontent.com/89058555/156918491-591eeb4c-612b-4290-837e-dbf91e5d22a6.png)
![Windows 7-2022-03-06-18-02-40](https://user-images.githubusercontent.com/89058555/156918496-fd6973ba-89a8-4eb0-8305-ad5a227f1463.png)

**Comment by oleg-sgh** [comment]
vxbmtu94516
I don't need a context menu. I use hotkeys.

**Comment by AlexanderPro** [comment]
@oleg-sgh,

Does version 2.19.3 work correctly with hotkeys for PotPlayer and similar programs?

**Comment by oleg-sgh** [comment]
> @oleg-sgh,
> 
> Does version 2.19.3 work correctly with hotkeys for PotPlayer and similar programs?

Yes, it works with PotPlayer and in Explorer dialog boxes, as in all MY programs.
The topic can be closed.

**Comment by AlexanderPro** [comment]
Thank you!
