### ISSUE TITLE
Doesnt work on cmd windows

### ISSUE THREAD

**Issue by TingTingin** [AlexanderPro/SmartSystemMenu#73]
I cant seem to get this to work on cmd windows im not sure what im doing wrong since i does work sometimes but extremely rarely

**Comment by AlexanderPro** [comment]
What version do you use? Can you try v2.19.3 and v2.18.0 and compare them?

**Comment by TingTingin** [comment]
I upgraded to the recent version after posting the comment and saw that its working again but this has happened before hopefully it keeps working

**Comment by AlexanderPro** [comment]
@TingTingin,

Does version 2.19.3 work correctly?

**Comment by TingTingin** [comment]
yeah it still is

**Comment by AlexanderPro** [comment]
Only cmd windows?

**Comment by TingTingin** [comment]
No when is said this "I upgraded to the recent version after posting the comment and saw that its working again but this has happened before hopefully it keeps working" I meant I saw that it worked again on cmd windows as well as others i should have been more clear

**Comment by AlexanderPro** [comment]
Ok, thanks. Can this issue be closed?

**Comment by TingTingin** [comment]
yeah thx
