### ISSUE TITLE
2.20 can't minimize the app to tray while 2.19 or older versions can

### ISSUE THREAD

**Issue by netsonicyxf** [AlexanderPro/SmartSystemMenu#75]
MediaCoderAutoAnswer.exe.zip contains a MediaCoderAutoAnswer.exe file that 2.20 can't minimize the app to tray while 2.19 or older versions can.
MediaCoderAutoAnswer.sha256.zip contains a sha265 for MediaCoderAutoAnswer.exe.

I use virustotal to verify the MediaCode rAutoAnswer.exe is clean. https://www.virustotal.com/gui/file/44a1854312448516830aadd64bed36d488729df97faad06e88a597b9dcea8dea/detection
You can also verify the sha265 in here
https://www.virustotal.com/gui/file/44a1854312448516830aadd64bed36d488729df97faad06e88a597b9dcea8dea/details

[MediaCoderAutoAnswer.exe.zip](https://github.com/AlexanderPro/SmartSystemMenu/files/8460278/MediaCoderAutoAnswer.exe.zip)
[MediaCoderAutoAnswer.sha256.zip](https://github.com/AlexanderPro/SmartSystemMenu/files/8460280/MediaCoderAutoAnswer.sha256.zip)

**Comment by AlexanderPro** [comment]
Try version  [2.20.1](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.20.1/SmartSystemMenu_v2.20.1.zip)

**Comment by netsonicyxf** [comment]
Thanks, it works.
