### ISSUE TITLE
question about translation

### ISSUE THREAD

**Issue by SaiyajinK** [AlexanderPro/SmartSystemMenu#86]
Hello, 

I can't integrate a new translation into the program (french), all tags in -Language.xml- are correct, but the new language is not displayed in the program (when I replace an existing one it works but there is no point in doing it like that).

Otherwise, more simply, how to propose this translation to the dev?

Thank you !

**Comment by AlexanderPro** [comment]
Hi SaiyajinK,

Please, make PR with Language.xml file and I will do the necessary corrections. Thank you!

**Comment by SaiyajinK** [comment]
Hi,

Not knowing what "PR" means (sorry ^^*), i attached the -language.xml- file with the french translation to .zip : 
> [language.xml_with_fr_translation.zip](https://github.com/AlexanderPro/SmartSystemMenu/files/8942866/language.xml_with_fr_translation.zip)

I remain available if needed. :+1:

**Comment by AlexanderPro** [comment]
Please, try version [2.21.1](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.21.1/SmartSystemMenu_v2.21.1.zip)

**Comment by AlexanderPro** [comment]
Ok, many thanks. Can this issue be closed?
