### ISSUE TITLE
Uncheck Alignment in Setting -> Menu (save)  not work

### ISSUE THREAD

**Issue by nindyaime** [AlexanderPro/SmartSystemMenu#92]
With Alignment Setting OFF in menu (Save),  SmartSystemMenu always save position in XML file, when I click save in any application.   So, when I run that application again, it shows based on that position.

I do not want application position to be saved.

**Comment by AlexanderPro** [comment]
Hi [nindyaime](https://github.com/nindyaime),

Thank you for finding the error. Please, try version  [2.21.2](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/v2.21.2/SmartSystemMenu_v2.21.2.zip)
