### ISSUE TITLE
[bug] no context menu with chrome except in default profile (through right-click)

### ISSUE THREAD

**Issue by uprprc777** [AlexanderPro/SmartSystemMenu#94]
No context menu pop up through right-click with chrome, except chrome under the default profile.

But it works properly with `alt+space`.

Make a another chrome profile and launch with this profile can easily reproduce this bug.

Also confirmed by me, no context menu with Windows Terminal UWP, neither right-click nor `alt+space`.

**Comment by AlexanderPro** [comment]
I can't reproduce the error either for Windows Terminal or Chrome on Windows 10 (Build 19044.2251). What OS do you use? And what Windows Terminal profile do you use?
