### ISSUE TITLE
[Request] Disable close button

### ISSUE THREAD

**Issue by mafrailea** [AlexanderPro/SmartSystemMenu#99]
Hi,

You application is really great, but I'm missing an option to remove the close button for specific application.

It would be really useful to avoid closing certain windows that you don't want to close, and I think it's something that you can really do programming-wise.

Maybe allowing to disable the other buttons (minimize and maximize) could be possible as well, but not something that I'm going to use for now.

Best regards,
Miguel

**Comment by AlexanderPro** [comment]
Hi [mafrailea](https://github.com/mafrailea),

Would you like a window to be closed by Alt+F4 at the same time?

**Comment by mafrailea** [comment]
Hi @AlexanderPro,

Well, I would prefer that Alt+F4 doesn't close the window, neither.

The idea is that, if you want to close that window, you need to re-enable the close button through your system menu.

Thanks a lot for taking this request into account. :)

**Comment by AlexanderPro** [comment]
Ok, I will add this feature soon.

**Comment by AlexanderPro** [comment]
[mafrailea](https://github.com/mafrailea), Please, try version [2.22.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v2.22.0). Unfortunately, I have not been able to suppress "Alt+F4" keys for "Close" button.

**Comment by mafrailea** [comment]
> [mafrailea](https://github.com/mafrailea), Please, try version [2.22.0](https://github.com/AlexanderPro/SmartSystemMenu/releases/tag/v2.22.0). Unfortunately, I have not been able to suppress "Alt+F4" keys for "Close" button.

No worries, I tested it and works great!

Thanks a lot!!
